#%RAML 1.0
baseUri: https://www.hmislynk.com/hmis-clientapi/rest/v2014
mediaType: application/json
protocols:
  -  HTTPS
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
title: 2014 HMIS
version: 1.0.0
types:
  affiliation : !include types/affiliation.json
  affiliation_id : !include types/affiliation_id.json
  affiliations_ids : !include types/affiliations_ids.json
  client : !include types/client.json
  client_id : !include types/client_id.json
  clients : !include types/clients.json
  clients_ids : !include types/clients_ids.json
  commercial_sexual_exploitation : !include types/commercial_sexual_exploitation.json
  commercial_sexual_exploitation_id : !include types/commercial_sexual_exploitation_id.json
  commercial_sexual_exploitations_ids : !include types/commercial_sexual_exploitations_ids.json
  connection_with_soar : !include types/connection_with_soar.json
  connection_with_soar_id : !include types/connection_with_soar_id.json
  connection_with_soars_ids : !include types/connection_with_soars_ids.json
  date_of_engagement : !include types/date_of_engagement.json
  date_of_engagement_id : !include types/date_of_engagement_id.json
  date_of_engagements_ids : !include types/date_of_engagements_ids.json
  disabilities_ids : !include types/disabilities_ids.json
  disability : !include types/disability.json
  disability_id : !include types/disability_id.json
  domestic_violence : !include types/domestic_violence.json
  domestic_violence_id : !include types/domestic_violence_id.json
  domestic_violences_ids : !include types/domestic_violences_ids.json
  employment : !include types/employment.json
  employment_id : !include types/employment_id.json
  employments : !include types/employments.json
  employments_ids : !include types/employments_ids.json
  enrollment : !include types/enrollment.json
  enrollment_coc : !include types/enrollment_coc.json
  enrollment_coc_id : !include types/enrollment_coc_id.json
  enrollment_cocs_ids : !include types/enrollment_cocs_ids.json
  enrollment_id : !include types/enrollment_id.json
  enrollments_ids : !include types/enrollments_ids.json
  exit : !include types/exit.json
  exit_housing_assessment : !include types/exit_housing_assessment.json
  exit_housing_assessment_id : !include types/exit_housing_assessment_id.json
  exit_housing_assessments_ids : !include types/exit_housing_assessments_ids.json
  exit_id : !include types/exit_id.json
  exit_plans_action : !include types/exit_plans_action.json
  exit_plans_action_id : !include types/exit_plans_action_id.json
  exit_plans_actions_ids : !include types/exit_plans_actions_ids.json
  exits_ids : !include types/exits_ids.json
  family_reunification : !include types/family_reunification.json
  family_reunification_id : !include types/family_reunification_id.json
  family_reunifications_ids : !include types/family_reunifications_ids.json
  former_ward_child_welfare : !include types/former_ward_child_welfare.json
  former_ward_child_welfare_id : !include types/former_ward_child_welfare_id.json
  former_ward_child_welfares_ids : !include types/former_ward_child_welfares_ids.json
  former_ward_juvenile_justice : !include types/former_ward_juvenile_justice.json
  former_ward_juvenile_justice_id : !include types/former_ward_juvenile_justice_id.json
  former_ward_juvenile_justices_ids : !include types/former_ward_juvenile_justices_ids.json
  funder : !include types/funder.json
  funder_id : !include types/funder_id.json
  funders_ids : !include types/funders_ids.json
  get_all_hmis_type_names : !include types/get_all_hmis_type_names.json
  get_all_hmis_type_value_of_hmis_type : !include types/get_all_hmis_type_value_of_hmis_type.json
  get_all_survey_questions : !include types/get_all_survey_questions.json
  get_survey_question_by_hud_id : !include types/get_survey_question_by_hud_id.json
  health_insurance : !include types/health_insurance.json
  health_insurance_id : !include types/health_insurance_id.json
  health_insurances_ids : !include types/health_insurances_ids.json
  health_status : !include types/health_status.json
  health_status_id : !include types/health_status_id.json
  health_statuses_ids : !include types/health_statuses_ids.json
  housing_assessment_disposition : !include types/housing_assessment_disposition.json
  housing_assessment_disposition_id : !include types/housing_assessment_disposition_id.json
  housing_assessment_dispositions_ids : !include types/housing_assessment_dispositions_ids.json
  income_and_source : !include types/income_and_source.json
  income_and_source_id : !include types/income_and_source_id.json
  income_and_sources_ids : !include types/income_and_sources_ids.json
  inventories_ids : !include types/inventories_ids.json
  inventory : !include types/inventory.json
  inventory_id : !include types/inventory_id.json
  last_grade_completed : !include types/last_grade_completed.json
  last_grade_completed_id : !include types/last_grade_completed_id.json
  last_grade_completeds_ids : !include types/last_grade_completeds_ids.json
  last_permanent_address : !include types/last_permanent_address.json
  last_permanent_address_id : !include types/last_permanent_address_id.json
  last_permanent_addresses_ids : !include types/last_permanent_addresses_ids.json
  medical_assistance : !include types/medical_assistance.json
  medical_assistance_id : !include types/medical_assistance_id.json
  medical_assistances_ids : !include types/medical_assistances_ids.json
  non_cash_benefits : !include types/non_cash_benefits.json
  non_cash_benefits_id : !include types/non_cash_benefits_id.json
  non_cash_benefitses_ids : !include types/non_cash_benefitses_ids.json
  organization : !include types/organization.json
  organization_id : !include types/organization_id.json
  organization_id_only : !include types/organization_id_only.json
  organizations_ids : !include types/organizations_ids.json
  path_status : !include types/path_status.json
  path_status_id : !include types/path_status_id.json
  path_statuses_ids : !include types/path_statuses_ids.json
  percent_ami : !include types/percent_ami.json
  percent_ami_id : !include types/percent_ami_id.json
  percent_amis_ids : !include types/percent_amis_ids.json
  project : !include types/project.json
  project_coc : !include types/project_coc.json
  project_coc_id : !include types/project_coc_id.json
  project_cocs_ids : !include types/project_cocs_ids.json
  project_completion_status : !include types/project_completion_status.json
  project_completion_status_id : !include types/project_completion_status_id.json
  project_completion_statuses_ids : !include types/project_completion_statuses_ids.json
  project_id : !include types/project_id.json
  projects_ids : !include types/projects_ids.json
  referral_source : !include types/referral_source.json
  referral_source_id : !include types/referral_source_id.json
  referral_sources_ids : !include types/referral_sources_ids.json
  residential_move_in : !include types/residential_move_in.json
  residential_move_in_id : !include types/residential_move_in_id.json
  residential_move_ins_ids : !include types/residential_move_ins_ids.json
  rhy_bcp_status : !include types/rhy_bcp_status.json
  rhy_bcp_status_id : !include types/rhy_bcp_status_id.json
  rhy_bcp_statuses_ids : !include types/rhy_bcp_statuses_ids.json
  school_status : !include types/school_status.json
  school_status_id : !include types/school_status_id.json
  school_statuses_ids : !include types/school_statuses_ids.json
  service : !include types/service.json
  service_id : !include types/service_id.json
  services_ids : !include types/services_ids.json
  sexual_orientation : !include types/sexual_orientation.json
  sexual_orientation_id : !include types/sexual_orientation_id.json
  sexual_orientations_ids : !include types/sexual_orientations_ids.json
  site : !include types/site.json
  site_id : !include types/site_id.json
  sites_ids : !include types/sites_ids.json
  veteran_info : !include types/veteran_info.json
  veteran_info_id : !include types/veteran_info_id.json
  veteran_infos_ids : !include types/veteran_infos_ids.json
  worst_housing_situation : !include types/worst_housing_situation.json
  worst_housing_situation_id : !include types/worst_housing_situation_id.json
  worst_housing_situations_ids : !include types/worst_housing_situations_ids.json
  youth_critical_issue : !include types/youth_critical_issue.json
  youth_critical_issue_id : !include types/youth_critical_issue_id.json
  youth_critical_issues_ids : !include types/youth_critical_issues_ids.json

resourceTypes:
  collection: !include types/collection.raml
  member: !include types/member.raml

/clients:
  type:
    collection:
      schema_ids: clients_ids
      schema_ids_example: !include examples/clients_ids_example.json
      schema: client
      schema_example: !include examples/client_example.json
      schema_id_example: !include examples/client_id_example.json
  /{clientid}:
    type:
       member:
        schema: client
        schema_id: client_id
        schema_id_example: !include examples/client_id_example.json
        schema_example: !include examples/client_example.json
    /enrollments:
      type:
        collection:
          schema_ids: enrollments_ids
          schema_ids_example: !include examples/enrollments_ids_example.json
          schema: enrollment
          schema_example: !include examples/enrollment_example.json
          schema_id_example: !include examples/enrollment_id_example.json
      /{enrollmentid}:
        type:
          member:
            schema: enrollment
            schema_id: enrollment_id
            schema_id_example: !include examples/enrollment_id_example.json
            schema_example: !include examples/enrollment_example.json
        /commercialsexualexploitations:
          type:
            collection:
              schema_ids: commercial_sexual_exploitations_ids
              schema_ids_example: !include examples/commercial_sexual_exploitations_ids_example.json
              schema: commercial_sexual_exploitation
              schema_example: !include examples/commercial_sexual_exploitation_example.json
              schema_id_example: !include examples/commercial_sexual_exploitation_id_example.json
          /{commercialsexualexploitationid}:
            type:
              member:
                schema: commercial_sexual_exploitation
                schema_id: commercial_sexual_exploitation_id
                schema_id_example: !include examples/commercial_sexual_exploitation_id_example.json
                schema_example: !include examples/commercial_sexual_exploitation_example.json
        /dateofengagements:
          type:
            collection:
              schema_ids: date_of_engagements_ids
              schema_ids_example: !include examples/date_of_engagements_ids_example.json
              schema: date_of_engagement
              schema_example: !include examples/date_of_engagement_example.json
              schema_id_example: !include examples/date_of_engagement_id_example.json
          /{dateofengagementid}:
            type:
              member:
                schema: date_of_engagement
                schema_id: date_of_engagement_id
                schema_id_example: !include examples/date_of_engagement_id_example.json
                schema_example: !include examples/date_of_engagement_example.json
        /disabilities:
          type:
            collection:
              schema_ids: disabilities_ids
              schema_ids_example: !include examples/disabilities_ids_example.json
              schema: disability
              schema_example: !include examples/disability_example.json
              schema_id_example: !include examples/disability_id_example.json
          /{disabilityid}:
            type:
              member:
                schema: disability
                schema_id: disability_id
                schema_id_example: !include examples/disability_id_example.json
                schema_example: !include examples/disability_example.json
        /domesticviolences:
          type:
            collection:
              schema_ids: domestic_violences_ids
              schema_ids_example: !include examples/domestic_violences_ids_example.json
              schema: domestic_violence
              schema_example: !include examples/domestic_violence_example.json
              schema_id_example: !include examples/domestic_violence_id_example.json
          /{domesticviolenceid}:
            type:
              member:
                schema: domestic_violence
                schema_id: domestic_violence_id
                schema_id_example: !include examples/domestic_violence_id_example.json
                schema_example: !include examples/domestic_violence_example.json
        /employments:
          type:
            collection:
              schema_ids: employments_ids
              schema_ids_example: !include examples/employments_ids_example.json
              schema: employment
              schema_example: !include examples/employment_example.json
              schema_id_example: !include examples/employment_id_example.json
          /{employmentid}:
            type:
              member:
                schema: employment
                schema_id: employment_id
                schema_id_example: !include examples/employment_id_example.json
                schema_example: !include examples/employment_example.json
        /enrollmentcocs:
          type:
            collection:
              schema_ids: enrollment_cocs_ids
              schema_ids_example: !include examples/enrollment_cocs_ids_example.json
              schema: enrollment_coc
              schema_example: !include examples/enrollment_coc_example.json
              schema_id_example: !include examples/enrollment_coc_id_example.json
          /{enrollmentcocid}:
            type:
              member:
                schema: enrollment_coc
                schema_id: enrollment_coc_id
                schema_id_example: !include examples/enrollment_coc_id_example.json
                schema_example: !include examples/enrollment_coc_example.json
        /exits:
          type:
            collection:
              schema_ids: exits_ids
              schema_ids_example: !include examples/exits_ids_example.json
              schema: exit
              schema_example: !include examples/exit_example.json
              schema_id_example: !include examples/exit_id_example.json
          /{exitid}:
            type:
              member:
                schema: exit
                schema_id: exit_id
                schema_id_example: !include examples/exit_id_example.json
                schema_example: !include examples/exit_example.json
            /connectionwithsoars:
              type:
                collection:
                  schema_ids: connection_with_soars_ids
                  schema_ids_example: !include examples/connection_with_soars_ids_example.json
                  schema: connection_with_soar
                  schema_example: !include examples/connection_with_soar_example.json
                  schema_id_example: !include examples/connection_with_soar_id_example.json
              /{connectionwithsoarid}:
                type:
                  member:
                    schema: connection_with_soar
                    schema_id: connection_with_soar_id
                    schema_id_example: !include examples/connection_with_soar_id_example.json
                    schema_example: !include examples/connection_with_soar_example.json
            /exithousingassessments:
              type:
                collection:
                  schema_ids: exit_housing_assessments_ids
                  schema_ids_example: !include examples/exit_housing_assessments_ids_example.json
                  schema: exit_housing_assessment
                  schema_example: !include examples/exit_housing_assessment_example.json
                  schema_id_example: !include examples/exit_housing_assessment_id_example.json
              /{exithousingassessmentid}:
                type:
                  member:
                    schema: exit_housing_assessment
                    schema_id: exit_housing_assessment_id
                    schema_id_example: !include examples/exit_housing_assessment_id_example.json
                    schema_example: !include examples/exit_housing_assessment_example.json
            /exitplansactions:
              type:
                collection:
                  schema_ids: exit_plans_actions_ids
                  schema_ids_example: !include examples/exit_plans_actions_ids_example.json
                  schema: exit_plans_action
                  schema_example: !include examples/exit_plans_action_example.json
                  schema_id_example: !include examples/exit_plans_action_id_example.json
              /{exitplansactionid}:
                type:
                  member:
                    schema: exit_plans_action
                    schema_id: exit_plans_action_id
                    schema_id_example: !include examples/exit_plans_action_id_example.json
                    schema_example: !include examples/exit_plans_action_example.json
            /familyreunifications:
              type:
                collection:
                  schema_ids: family_reunifications_ids
                  schema_ids_example: !include examples/family_reunifications_ids_example.json
                  schema: family_reunification
                  schema_example: !include examples/family_reunification_example.json
                  schema_id_example: !include examples/family_reunification_id_example.json
              /{familyreunificationid}:
                type:
                  member:
                    schema: family_reunification
                    schema_id: family_reunification_id
                    schema_id_example: !include examples/family_reunification_id_example.json
                    schema_example: !include examples/family_reunification_example.json
            /housingassessmentdispositions:
              type:
                collection:
                  schema_ids: housing_assessment_dispositions_ids
                  schema_ids_example: !include examples/housing_assessment_dispositions_ids_example.json
                  schema: housing_assessment_disposition
                  schema_example: !include examples/housing_assessment_disposition_example.json
                  schema_id_example: !include examples/housing_assessment_disposition_id_example.json
              /{housingassessmentdispositionid}:
                type:
                  member:
                    schema: housing_assessment_disposition
                    schema_id: housing_assessment_disposition_id
                    schema_id_example: !include examples/housing_assessment_disposition_id_example.json
                    schema_example: !include examples/housing_assessment_disposition_example.json
            /projectcompletionstatuses:
              type:
                collection:
                  schema_ids: project_completion_statuses_ids
                  schema_ids_example: !include examples/project_completion_statuses_ids_example.json
                  schema: project_completion_status
                  schema_example: !include examples/project_completion_status_example.json
                  schema_id_example: !include examples/project_completion_status_id_example.json
              /{projectcompletionstatusid}:
                type:
                  member:
                    schema: project_completion_status
                    schema_id: project_completion_status_id
                    schema_id_example: !include examples/project_completion_status_id_example.json
                    schema_example: !include examples/project_completion_status_example.json
        /formerwardchildwelfares:
          type:
            collection:
              schema_ids: former_ward_child_welfares_ids
              schema_ids_example: !include examples/former_ward_child_welfares_ids_example.json
              schema: former_ward_child_welfare
              schema_example: !include examples/former_ward_child_welfare_example.json
              schema_id_example: !include examples/former_ward_child_welfare_id_example.json
          /{formerwardchildwelfareid}:
            type:
              member:
                schema: former_ward_child_welfare
                schema_id: former_ward_child_welfare_id
                schema_id_example: !include examples/former_ward_child_welfare_id_example.json
                schema_example: !include examples/former_ward_child_welfare_example.json
        /formerwardjuvenilejustices:
          type:
            collection:
              schema_ids: former_ward_juvenile_justices_ids
              schema_ids_example: !include examples/former_ward_juvenile_justices_ids_example.json
              schema: former_ward_juvenile_justice
              schema_example: !include examples/former_ward_juvenile_justice_example.json
              schema_id_example: !include examples/former_ward_juvenile_justice_id_example.json
          /{formerwardjuvenilejusticeid}:
            type:
              member:
                schema: former_ward_juvenile_justice
                schema_id: former_ward_juvenile_justice_id
                schema_id_example: !include examples/former_ward_juvenile_justice_id_example.json
                schema_example: !include examples/former_ward_juvenile_justice_example.json
        /healthinsurances:
          type:
            collection:
              schema_ids: health_insurances_ids
              schema_ids_example: !include examples/health_insurances_ids_example.json
              schema: health_insurance
              schema_example: !include examples/health_insurance_example.json
              schema_id_example: !include examples/health_insurance_id_example.json
          /{healthinsuranceid}:
            type:
              member:
                schema: health_insurance
                schema_id: health_insurance_id
                schema_id_example: !include examples/health_insurance_id_example.json
                schema_example: !include examples/health_insurance_example.json
        /healthstatuses:
          type:
            collection:
              schema_ids: health_statuses_ids
              schema_ids_example: !include examples/health_statuses_ids_example.json
              schema: health_status
              schema_example: !include examples/health_status_example.json
              schema_id_example: !include examples/health_status_id_example.json
          /{healthstatusid}:
            type:
              member:
                schema: health_status
                schema_id: health_status_id
                schema_id_example: !include examples/health_status_id_example.json
                schema_example: !include examples/health_status_example.json
        /incomeandsources:
          type:
            collection:
              schema_ids: income_and_sources_ids
              schema_ids_example: !include examples/income_and_sources_ids_example.json
              schema: income_and_source
              schema_example: !include examples/income_and_source_example.json
              schema_id_example: !include examples/income_and_source_id_example.json
          /{incomeandsourceid}:
            type:
              member:
                schema: income_and_source
                schema_id: income_and_source_id
                schema_id_example: !include examples/income_and_source_id_example.json
                schema_example: !include examples/income_and_source_example.json
        /lastgradecompleteds:
          type:
            collection:
              schema_ids: last_grade_completeds_ids
              schema_ids_example: !include examples/last_grade_completeds_ids_example.json
              schema: last_grade_completed
              schema_example: !include examples/last_grade_completed_example.json
              schema_id_example: !include examples/last_grade_completed_id_example.json
          /{lastgradecompletedid}:
            type:
              member:
                schema: last_grade_completed
                schema_id: last_grade_completed_id
                schema_id_example: !include examples/last_grade_completed_id_example.json
                schema_example: !include examples/last_grade_completed_example.json
        /lastpermanentaddresses:
          type:
            collection:
              schema_ids: last_permanent_addresses_ids
              schema_ids_example: !include examples/last_permanent_addresses_ids_example.json
              schema: last_permanent_address
              schema_example: !include examples/last_permanent_address_example.json
              schema_id_example: !include examples/last_permanent_address_id_example.json
          /{lastpermanentaddressid}:
            type:
              member:
                schema: last_permanent_address
                schema_id: last_permanent_address_id
                schema_id_example: !include examples/last_permanent_address_id_example.json
                schema_example: !include examples/last_permanent_address_example.json
        /medicalassistances:
          type:
            collection:
              schema_ids: medical_assistances_ids
              schema_ids_example: !include examples/medical_assistances_ids_example.json
              schema: medical_assistance
              schema_example: !include examples/medical_assistance_example.json
              schema_id_example: !include examples/medical_assistance_id_example.json
          /{medicalassistanceid}:
            type:
              member:
                schema: medical_assistance
                schema_id: medical_assistance_id
                schema_id_example: !include examples/medical_assistance_id_example.json
                schema_example: !include examples/medical_assistance_example.json
        /noncashbenefits:
          type:
            collection:
              schema_ids: non_cash_benefitses_ids
              schema_ids_example: !include examples/non_cash_benefitses_ids_example.json
              schema: non_cash_benefits
              schema_example: !include examples/non_cash_benefits_example.json
              schema_id_example: !include examples/non_cash_benefits_id_example.json
          /{noncashbenefitid}:
            type:
              member:
                schema: non_cash_benefits
                schema_id: non_cash_benefits_id
                schema_id_example: !include examples/non_cash_benefits_id_example.json
                schema_example: !include examples/non_cash_benefits_example.json
        /referralsources:
          type:
            collection:
              schema_ids: referral_sources_ids
              schema_ids_example: !include examples/referral_sources_ids_example.json
              schema: referral_source
              schema_example: !include examples/referral_source_example.json
              schema_id_example: !include examples/referral_source_id_example.json
          /{referralsourceid}:
            type:
              member:
                schema: referral_source
                schema_id: referral_source_id
                schema_id_example: !include examples/referral_source_id_example.json
                schema_example: !include examples/referral_source_example.json
        /residentialmoveins:
          type:
            collection:
              schema_ids: residential_move_ins_ids
              schema_ids_example: !include examples/residential_move_ins_ids_example.json
              schema: residential_move_in
              schema_example: !include examples/residential_move_in_example.json
              schema_id_example: !include examples/residential_move_in_id_example.json
          /{residentialmoveinid}:
            type:
              member:
                schema: residential_move_in
                schema_id: residential_move_in_id
                schema_id_example: !include examples/residential_move_in_id_example.json
                schema_example: !include examples/residential_move_in_example.json
        /rhybcpstatuses:
          type:
            collection:
              schema_ids: rhy_bcp_statuses_ids
              schema_ids_example: !include examples/rhy_bcp_statuses_ids_example.json
              schema: rhy_bcp_status
              schema_example: !include examples/rhy_bcp_status_example.json
              schema_id_example: !include examples/rhy_bcp_status_id_example.json
          /{rhybcpstatusid}:
            type:
              member:
                schema: rhy_bcp_status
                schema_id: rhy_bcp_status_id
                schema_id_example: !include examples/rhy_bcp_status_id_example.json
                schema_example: !include examples/rhy_bcp_status_example.json
        /pathstatuses:
          type:
            collection:
              schema_ids: path_statuses_ids
              schema_ids_example: !include examples/path_statuses_ids_example.json
              schema: path_status
              schema_example: !include examples/path_status_example.json
              schema_id_example: !include examples/path_status_id_example.json
          /{pathstatusid}:
            type:
              member:
                schema: path_status
                schema_id: path_status_id
                schema_id_example: !include examples/path_status_id_example.json
                schema_example: !include examples/path_status_example.json
        /percentamis:
          type:
            collection:
              schema_ids: percent_amis_ids
              schema_ids_example: !include examples/percent_amis_ids_example.json
              schema: percent_ami
              schema_example: !include examples/percent_ami_example.json
              schema_id_example: !include examples/percent_ami_id_example.json
          /{percentamiid}:
            type:
              member:
                schema: percent_ami
                schema_id: percent_ami_id
                schema_id_example: !include examples/percent_ami_id_example.json
                schema_example: !include examples/percent_ami_example.json
        /schoolstatuses:
          type:
            collection:
              schema_ids: school_statuses_ids
              schema_ids_example: !include examples/school_statuses_ids_example.json
              schema: school_status
              schema_example: !include examples/school_status_example.json
              schema_id_example: !include examples/school_status_id_example.json
          /{schoolstatusid}:
            type:
              member:
                schema: school_status
                schema_id: school_status_id
                schema_id_example: !include examples/school_status_id_example.json
                schema_example: !include examples/school_status_example.json
        /services:
          type:
            collection:
              schema_ids: services_ids
              schema_ids_example: !include examples/services_ids_example.json
              schema: service
              schema_example: !include examples/service_example.json
              schema_id_example: !include examples/service_id_example.json
          /{serviceid}:
            type:
              member:
                schema: service
                schema_id: service_id
                schema_id_example: !include examples/service_id_example.json
                schema_example: !include examples/service_example.json
        /sexualorientations:
          type:
            collection:
              schema_ids: sexual_orientations_ids
              schema_ids_example: !include examples/sexual_orientations_ids_example.json
              schema: sexual_orientation
              schema_example: !include examples/sexual_orientation_example.json
              schema_id_example: !include examples/sexual_orientation_id_example.json
          /{sexualorientationid}:
            type:
              member:
                schema: sexual_orientation
                schema_id: sexual_orientation_id
                schema_id_example: !include examples/sexual_orientation_id_example.json
                schema_example: !include examples/sexual_orientation_example.json
        /worsthousingsituations:
          type:
            collection:
              schema_ids: worst_housing_situations_ids
              schema_ids_example: !include examples/worst_housing_situations_ids_example.json
              schema: worst_housing_situation
              schema_example: !include examples/worst_housing_situation_example.json
              schema_id_example: !include examples/worst_housing_situation_id_example.json
          /{worsthousingsituationid}:
            type:
              member:
                schema: worst_housing_situation
                schema_id: worst_housing_situation_id
                schema_id_example: !include examples/worst_housing_situation_id_example.json
                schema_example: !include examples/worst_housing_situation_example.json
        /youthcriticalissues:
          type:
            collection:
              schema_ids: youth_critical_issues_ids
              schema_ids_example: !include examples/youth_critical_issues_ids_example.json
              schema: youth_critical_issue
              schema_example: !include examples/youth_critical_issue_example.json
              schema_id_example: !include examples/youth_critical_issue_id_example.json
          /{youthcriticalissueid}:
            type:
              member:
                schema: youth_critical_issue
                schema_id: youth_critical_issue_id
                schema_id_example: !include examples/youth_critical_issue_id_example.json
                schema_example: !include examples/youth_critical_issue_example.json
    /veteraninfos:
      type:
        collection:
          schema_ids: veteran_infos_ids
          schema_ids_example: !include examples/veteran_infos_ids_example.json
          schema: veteran_info
          schema_example: !include examples/veteran_info_example.json
          schema_id_example: !include examples/veteran_info_id_example.json
      /{veteraninfoid}:
        type:
          member:
            schema: veteran_info
            schema_id: veteran_info_id
            schema_id_example: !include examples/veteran_info_id_example.json
            schema_example: !include examples/veteran_info_example.json
/organizations:
  type:
    collection:
      schema_ids: organizations_ids
      schema_ids_example: !include examples/organizations_ids_example.json
      schema: organization
      schema_example: !include examples/organization_example.json
      schema_id_example: !include examples/organization_id_example.json
  /{organizationid}:
    type:
      member:
        schema: organization
        schema_id: organization_id
        schema_id_example: !include examples/organization_id_example.json
        schema_example: !include examples/organization_example.json
/projects:
  type:
    collection:
      schema_ids: projects_ids
      schema_ids_example: !include examples/projects_ids_example.json
      schema: project
      schema_example: !include examples/project_example.json
      schema_id_example: !include examples/project_id_example.json
  /{projectid}:
    type:
      member:
        schema: project
        schema_id: project_id
        schema_id_example: !include examples/project_id_example.json
        schema_example: !include examples/project_example.json
    /affiliations:
      type:
        collection:
          schema_ids: affiliations_ids
          schema_ids_example: !include examples/affiliations_ids_example.json
          schema: affiliation
          schema_example: !include examples/affiliation_example.json
          schema_id_example: !include examples/affiliation_id_example.json
      /{affiliationid}:
        type:
          member:
            schema: affiliation
            schema_id: affiliation_id
            schema_id_example: !include examples/affiliation_id_example.json
            schema_example: !include examples/affiliation_example.json
    /funders:
      type:
        collection:
          schema_ids: funders_ids
          schema_ids_example: !include examples/funders_ids_example.json
          schema: funder
          schema_example: !include examples/funder_example.json
          schema_id_example: !include examples/funder_id_example.json
      /{funderid}:
        type:
          member:
            schema: funder
            schema_id: funder_id
            schema_id_example: !include examples/funder_id_example.json
            schema_example: !include examples/funder_example.json
    /inventories:
      type:
        collection:
          schema_ids: inventories_ids
          schema_ids_example: !include examples/inventories_ids_example.json
          schema: inventory
          schema_example: !include examples/inventory_example.json
          schema_id_example: !include examples/inventory_id_example.json
      /{inventoryid}:
        type:
          member:
            schema: inventory
            schema_id: inventory_id
            schema_id_example: !include examples/inventory_id_example.json
            schema_example: !include examples/inventory_example.json
    /projectcocs:
      type:
        collection:
          schema_ids: project_cocs_ids
          schema_ids_example: !include examples/project_cocs_ids_example.json
          schema: project_coc
          schema_example: !include examples/project_coc_example.json
          schema_id_example: !include examples/project_coc_id_example.json
      /{projectcocid}:
        type:
          member:
            schema: project_coc
            schema_id: project_coc_id
            schema_id_example: !include examples/project_coc_id_example.json
            schema_example: !include examples/project_coc_example.json
    /sites:
      type:
        collection:
          schema_ids: sites_ids
          schema_ids_example: !include examples/sites_ids_example.json
          schema: site
          schema_example: !include examples/site_example.json
          schema_id_example: !include examples/site_id_example.json
      /{siteid}:
        type:
          member:
            schema: site
            schema_id: site_id
            schema_id_example: !include examples/site_id_example.json
            schema_example: !include examples/site_example.json
/search/{searchentity}:
  get:
    description: |
          The Search API is optimized to find the specific entity you're looking for (e.g., a client, enrollments, etc.).It's designed to  find the one result you're looking for (or maybe the few results you're looking for). Currently hmislynk supporting search on 'clients'  and 'projects' entities only. Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs.  HMISLynk Search API provides up to 50 results for each searh. However, the search results can be limited by the client.
            Note: 1) API currently supports search on client and project entities
                  2) URIs are /search/clients and /search/projects
    queryParameters:
      q:
        description: |
             The search keywords for clients, as well as any qualifiers.Currently supported search fields are first name,middle name,last name,dob,source system id, client's dedup Id and ssn. For search on "date of birth" field the format MM/dd/YYYY should be used for the search keyword. When searched on dedup Id, the API returns the list of all clients (from all the schema years) that has the same dedup Id.

             The seach keywords for projects, as well as any qualifiers. Currenly supported search fields are projectName, projectCommonName, projectId.
      sort:
        description: The sort field. Default- results are sorted by "created date".
        type: string
        example: created date
      order:
        description: The sort order if sort parameter is provided. One of asc or desc. Default- desc.
        type: string
        example: desc
        default: desc
      startIndex:
        description: The start Index from where the search results should be returned. Default - 0
        type: integer
        example: 0
        default: 0
      maxItems:
        description: the number or Items that should be included in the results . Default - 50
        type: integer
        example: 50
        default: 50
      exclude:
         description: |
            Excludes fields from the search.Currently it suppoted value is "ssi" (to exclude source system id) only.
    responses:
      200:
        body:
          description: |
            sample search responses for client and project searches
            {
            "searchResults": {
              "pagination": {
                "total":"2",
                "from": "0",
                "maximum": "50",
                "returned":"2"
              },
              "items": [
                {
                  "clientId": "65e3df62-dd22-4d07-83ef-6858a6322839",
                  "firstName": "Eric",
                  "middleName": "Johnstone",
                  "lastName": "Smith",
                  "nameSuffix": "Jr.",
                  "nameDataQuality": "1",
                  "ssn": "ssn ",
                  "ssnDataQuality": "1",
                  "dob": "1459498034983",
                  "dobDataQuality": "1",
                  "race": "1",
                  "ethnicity": "1",
                  "gender": "1",
                  "otherGender": "Test",
                  "veteranStatus": "8",
                  "phoneNumber":"1-541-754-3010",
                  "emailAddress":"Jeanette@gmail.com",
                  "link":"/hmis-clientapi/rest/v2015/clients/65e3df62-dd22-4d07-83ef-6858a6322839"
                },
                {
                  "clientId": "cf98b9b2-9a77-4133-99a3-b60f05a12ad1",
                  "firstName": "Harold",
                  "middleName": "William",
                  "lastName": "Jones",
                  "nameSuffix": "III ",
                  "nameDataQuality": "1",
                  "ssn": "ssn ",
                  "ssnDataQuality": "1",
                  "dob": "1459498034983",
                  "dobDataQuality": "1",
                  "race": "1",
                  "ethnicity": "1",
                  "gender": "1",
                  "otherGender": "Test",
                  "veteranStatus": "8",
                  "link":"/hmis-clientapi/rest/v2014/clients/cf98b9b2-9a77-4133-99a3-b60f05a12ad1"
                }
              ]
            }
            }

            {
              "searchResults":{
                "pagination":{
                  "from":0,
                  "returned":1,
                  "total":1,
                  "maximum":50,
                  "sort":{
                    "field":"id",
                    "order":"asc"
                  }
                },
                "items":[
                  {
                    "projectId":"066c95d3-c97c-40b9-b8c1-bf12cafdfca4",
                    "projectName":"ProjectName_1459515376900",
                    "projectCommonName":"ProjectCommonName_1459515376900,
                    "continuumProject":0,
                    "projectType":2,
                    "targetPopulation":3,
                    "trackingMethod":0,
                    "schemaYear":2015,
                    "link":"/hmis-clientapi/rest/v2015/projects/066c95d3-c97c-40b9-b8c1-bf12cafdfca4",
                    "projectGroup":"HO0002"
                  }
                ]
              }
            }
/dataelements:
  description: Get all available data elements
  get:
    responses:
      200:
        body:
          application/json:
             example: !include examples/get_all_hmis_type_names_example.json
             type: !include types/get_all_hmis_type_names.json
  /{name}/values:
    description:  get all values of elements
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_all_hmis_type_value_of_hmis_type_example.json
              type: !include types/get_all_hmis_type_value_of_hmis_type.json

/questions:
  description:  get all HUD Questions
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_all_survey_questions_example.json
            type: !include types/get_all_survey_questions.json
  /{hudQuestionId}:
    description:  get HUD Question by hudQuestionId
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_survey_question_by_hud_id_example.json
              type: !include types/get_survey_question_by_hud_id.json
